---
title: "CLOMP dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll

---

# loading data and functions
```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(shiny)
library(c3)
library(formattable)
library(DT)
library(reactable)

    prep_data<-function(path, taxa_class){
        #setwd(path)
        
        files<-list.files(path, pattern = '*.tsv',full.names = TRUE)
        
 
        
        
        for(i in 1:length(files)){
            #print(files[i])
            temp_tsv<-read.csv(files[i], sep = "\t", col.names = c('percent_clade_reads', 'number_clade_reads_rooted_at_taxon','number_clade_reads_this_taxon', 'taxa', 'taxid', 'name'), header = FALSE)
            total_reads = temp_tsv$number_clade_reads_rooted_at_taxon[2] + temp_tsv$number_clade_reads_rooted_at_taxon[1]
            temp_tsv$RPM = temp_tsv$number_clade_reads_this_taxon  / (total_reads / 1e6)
            temp_tsv$cumulative_RPM<-temp_tsv$number_clade_reads_rooted_at_taxon / (total_reads / 1e6)
            temp_tsv$taxa<-trimws(temp_tsv$taxa , which = "both", whitespace = "\t")
            temp_tsv$name<-as.character(temp_tsv$name)
            file_name = strsplit(files[i],"_L001")[[1]][1]
            
            #initialize dataframe for below
            if( i == 1 ){ 
                final_tsv<-temp_tsv[,c(4,5,6,8)] 
                colnames(final_tsv)[4]<-file_name
            }
            
            else{ 
                final_tsv[,(i+3)]<-0
                new_list<-c()
                for(j in 1:nrow(temp_tsv)){ 
                    #index is which row of the current pavian tsv equals the current taxid
                    index<-which(temp_tsv[j,5] == final_tsv[,2])
                    
                    if(identical(index, integer(0))){ 
                        final_tsv[(nrow(final_tsv)+ 2), ]<- 0
                        final_tsv[nrow(final_tsv),1]<-temp_tsv[j,4]
                        final_tsv[nrow(final_tsv),2]<-temp_tsv[j,5]
                        final_tsv[nrow(final_tsv),3]<-as.character(temp_tsv[j,6])
                        final_tsv[nrow(final_tsv),ncol(final_tsv)]<-temp_tsv[j,8]
                        
                        next
                    }
                    else{ 
                        final_tsv[index,i+3]<-temp_tsv[j,8]
                    }
                    colnames(final_tsv)[i+3]<-file_name
                }
            }
        }
        
        
        final_tsv<-final_tsv[complete.cases(final_tsv),]
        
        to_remove<-c()
        
        for(i in 1:nrow(final_tsv)){ 
            if( all(final_tsv[i,3:ncol(final_tsv)] == 0 )){ 
                to_remove<-append(to_remove, i)
            }
        }
        if(length(to_remove > 0)){
            final_tsv_zero_removed<-final_tsv[-to_remove,]
        }
        else{
            final_tsv_zero_removed<-final_tsv
        }
        
        taxa_filtered<-final_tsv_zero_removed[which(grepl(paste(taxa_class,collapse="|"),final_tsv_zero_removed$taxa)),]
        # 
        # sample_list<-c()
        # taxa_list<-c()
        # rpm_list<-c()
        # taxid_list<-c()
        # name_list<-c()
        # for(i in 1:nrow(final_tsv_zero_removed)){ 
        #     for(j in 4:ncol(final_tsv_zero_removed)){ 
        #         sample_list<-append(sample_list,colnames(final_tsv_zero_removed)[j])
        #         taxa_list<-append(taxa_list,final_tsv_zero_removed[i,1])
        #         rpm_list<-append(rpm_list,final_tsv_zero_removed[i,j])
        #         taxid_list<-append(taxid_list,final_tsv_zero_removed[i,2])
        #         name_list<-append(name_list, final_tsv_zero_removed[i,3])
        #     }  
        # }
        # accumulated_df<-as.data.frame(cbind(sample_list,taxa_list,rpm_list,taxid_list,name_list))
        # graph_df<-accumulated_df[which(accumulated_df$taxa_list == 'G'),]
        # 
        # graph_df$rpm_list<-as.numeric(as.character(graph_df$rpm_list))
        # graph_df$rpm_list<-round(graph_df$rpm_list, digits = 0)
        # 
        # graph_df$taxid_list<-as.character(graph_df$taxid_list)
        # graph_df<-graph_df[-which(graph_df$taxid_list == '9605'),]
        
        return(taxa_filtered)
    }
 filepath  = '/Users/vikas/Documents/UW/Greninger_lab/clomp_viz/scratch/remove_euk_test/'
  
        df<-(prep_data(filepath, 'S'))
        colnames(df)<-gsub("\t", "", colnames(df))
        df$name<-trimws(df$name, which = c("left"), whitespace = "[ \t\n]")


```


-------------------------------------
    
### RPM overview chart
    
```{r,fig.height=6}
       titlePanel("RPM overview")

    numericInput("RPM_threshold", "Minmum RPM threshold for filtering", 200, min = 1)
    checkboxInput('show_subchart', 'Show subchart', value = FALSE, width = NULL)

    renderC3({
            
        
        to_remove<-c()
        
        for(i in 1:nrow(df)){ 
            if(all(df[i,(4:ncol(df))] < input$RPM_threshold)){ 
                to_remove<-append(to_remove, i)
            }
        }
        if(length(to_remove > 0)){
            df<-df[-to_remove,]
        }
        
        
        
        #comment out when done with test_set
        
        trimmed_colnames<-c()
        for(i in 1:length(colnames(df))){ 
          if(grepl('//',colnames(df)[i])){
          trimmed_colnames<-append(trimmed_colnames,strsplit(colnames(df)[i], '//')[[1]][2])
          }
        }
        colnames(df)[4:ncol(df)]<-trimmed_colnames
        df<-df[,c(2:ncol(df))]
        data_df<-t(df[,c(3:ncol(df))])
        colnames(data_df)<-as.character(df[,2])
        #colnames(data_df)<-gsub("[[:space:]]", "", colnames(data_df))
        sample_names<-as.character(rownames(data_df))
        #taxa_names<-gsub("[[:space:]]", "", colnames(data_df))
        data_df<-log10(data_df + 1)
        
        
        
        if(input$show_subchart){ 
        data.frame(data_df) %>%
            c3() %>% 
            c3_bar(stacked = FALSE, rotated = FALSE, zerobased = TRUE)%>% 
            tooltip( grouped = FALSE) %>%
            xAxis( type = 'category', categories = sample_names, rotate = 45)  %>%
            legend(position = 'bottom') %>%
            zoom(type = 'scroll') %>% 
            subchart(height = 60)
        }
        else {        data.frame(data_df) %>%
                c3() %>% 
                c3_bar(stacked = FALSE, rotated = FALSE, zerobased = TRUE)%>% 
                tooltip( grouped = FALSE) %>%
                xAxis( type = 'category', categories = sample_names, rotate = 45)  %>%
                yAxis(label = 'log10(RPM)') %>%
                legend(position = 'bottom') %>%
                zoom(type = 'scroll') 
            }
    })

```
   
 
-------------------------------------

   
### RPM table


```{r, fig.height= 10} 
numericInput("Comparison_threshold", "Minmum RPM threshold for filtering", 10, min = 1)
checkboxGroupInput('phyloRank', 'Rank', c('D','P','C','O','F','G','S'), selected = c('D','P','C','O','F','G','S'), inline = TRUE)
renderReactable({
  
        comparison_df<-(prep_data(filepath, input$phyloRank))
        #comparison_df$taxa 
        to_remove<-c()
        
        for(i in 1:nrow(comparison_df)){ 
            if(all(comparison_df[i,(4:ncol(comparison_df))] < input$Comparison_threshold)){ 
                to_remove<-append(to_remove, i)
            }
        }
        if(length(to_remove > 0)){
            comparison_df<-comparison_df[-to_remove,]
        }
        trimmed_colnames<-c()
        for(i in 1:length(colnames(comparison_df))){ 
          if(grepl('//',colnames(comparison_df)[i])){
          trimmed_colnames<-append(trimmed_colnames,strsplit(colnames(comparison_df)[i], '//')[[1]][2])
          }
        }
        colnames(comparison_df)[4:ncol(comparison_df)]<-trimmed_colnames
        #comparison_df[4:ncol(comparison_df)]<-round(comparison_df[4:ncol(comparison_df)],0)
        #works but can't sort. Probably need to add buttons to patch it together (formattable is static and datatable is uggo)
        #datatable(formattable(comparison_df))
        
        graph_df<-comparison_df[,-c(1:2)]
        rownames(graph_df)<-graph_df[,1]
        graph_df$name<-NULL
GnYlRd <- function(x) rgb(colorRamp(c("#63be7b", "#ffeb84", "#f8696b"))(x), maxColorValue = 255)
        reactable(graph_df,
                  defaultColDef = colDef(
                  style = function(value) {
                    if (!is.numeric(value)) return()
                    normalized <- (value - min(graph_df)) / (max(graph_df) - min(graph_df))
                    color <- GnYlRd(normalized)
                    list(background = color)
                  },
                  format = colFormat(digits = 1),
                  minWidth = 50
                ),
                searchable = TRUE, 
                height = 500,
                bordered = FALSE,
                outlined = FALSE,
                resizable = TRUE,
                highlight = TRUE,
                fullWidth = TRUE,
                columns = list(
    .rownames = colDef(name = "Taxa", sortable = TRUE, align = "left",
    cell = function(value, index) {
    # Render as a link
    url <- sprintf("https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=%s", comparison_df$taxid[index])
    htmltools::tags$a(href = url, target = "_blank", as.character(value))
    #https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5606&lvl=3&lin=f&keep=1&srchmode=1&unlock
  })
        ))

})


```   
 
#SANKEY TIME YO
